#!/usr/bin/env python3
"""Dev server for ~/forest: like `python3 -m http.server` but with caching disabled (so edits to
viewer/src/*.js show up on a plain reload) and one write endpoint the dev page uses:

    POST /dev/save-params   body {"params": {...}, "ranges": {...}}
        → rewrites viewer/src/params-defaults.js (the tunables' defaults + grid ranges)

Localhost only.
    python3 viewer/serve.py            # from ~/forest → http://localhost:8000/viewer/dev.html
"""
import json, sys
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULTS_FILE = ROOT / "viewer" / "src" / "params-defaults.js"


def write_defaults(params: dict, ranges: dict) -> None:
    body = json.dumps(params, indent=2)
    rng = json.dumps(ranges, indent=2) if ranges else "{}"
    DEFAULTS_FILE.write_text(
        '// GENERATED by the dev page ("save as defaults") — values only. Do not hand-edit; use the sliders\n'
        "// and save, or edit and reload. What each key means is documented in params.js.\n"
        f"export default {body};\n\n"
        "// Grid / Forest default ranges: { key: [min, max] }. Keys absent here start fixed at the value above.\n"
        f"export const RANGES = {rng};\n",
        encoding="utf-8",
    )


class Handler(SimpleHTTPRequestHandler):
    def end_headers(self):
        self.send_header("Cache-Control", "no-store, must-revalidate")
        self.send_header("Expires", "0")
        super().end_headers()

    def log_message(self, fmt, *args):      # quieter: only non-200s
        if not (len(args) > 1 and str(args[1]).startswith(("200", "304"))):
            super().log_message(fmt, *args)

    def do_GET(self):
        if self.path == "/dev/ping":               # the dev page hides "save as defaults" when this 404s (static hosting)
            out = b'{"ok": true}'
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(out)))
            self.end_headers()
            self.wfile.write(out)
            return
        super().do_GET()

    def do_POST(self):
        if self.path != "/dev/save-params":
            self.send_error(404); return
        try:
            data = json.loads(self.rfile.read(int(self.headers.get("Content-Length", 0))))
            params, ranges = data["params"], data.get("ranges", {})
            if not isinstance(params, dict) or "nMax" not in params:
                raise ValueError("not a params object")
            write_defaults(params, ranges)
            out = json.dumps({"ok": True, "file": str(DEFAULTS_FILE.relative_to(ROOT))}).encode()
            self.send_response(200)
        except Exception as e:  # noqa: BLE001 — report anything to the page
            out = json.dumps({"ok": False, "error": str(e)}).encode()
            self.send_response(400)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(out)))
        self.end_headers()
        self.wfile.write(out)
        print("saved" if b'"ok": true' in out else out.decode(), DEFAULTS_FILE.name)


if __name__ == "__main__":
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 8000
    handler = lambda *a, **k: Handler(*a, directory=str(ROOT), **k)
    print(f"serving {ROOT} at http://localhost:{port}/viewer/dev.html  (no-cache, POST /dev/save-params)")
    ThreadingHTTPServer(("127.0.0.1", port), handler).serve_forever()
